nodeLinker: pnp

npmScopes:
  difuks:
    npmAuthToken: "${PERSONAL_NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  react-cosmos-plugin@*:
    dependencies:
      glob: "*"
      resolve-from: "*"
  webpack-dev-middleware@*:
    dependencies:
      webpack: "*"
  "@nestjs-modules/mailer@*":
    dependencies:
      tslib: "*"
      lodash: "*"
  "@nestlab/google-recaptcha@*":
    dependencies:
      axios: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.2.0.cjs
