name: 'Run node container'
description: 'Run node container'
inputs:
  script:
    description: 'Script for run'
    required: true
  detached:
    description: 'Detached docker mode'
    required: false
  secret-context:
    description: 'Secret params'
    required: true

runs:
  using: composite
  steps:
    - name: Run node script
      uses: ./.github/actions/ssh-script
      with:
        secret-context: ${{ inputs.secret-context }}
        script: |
          docker run --name fuks-blog \
          --rm ${{ inputs.detached && '-d' }} \
          -e FUKS_BLOG_AUTH_POSTGRES_PASSWORD="${FUKS_BLOG_AUTH_POSTGRES_PASSWORD}" \
          -e FUKS_BLOG_AUTH_POSTGRES_USER="${FUKS_BLOG_AUTH_POSTGRES_USER}" \
          -e FUKS_BLOG_AUTH_POSTGRES_HOST="${FUKS_BLOG_AUTH_POSTGRES_HOST}" \
          -e FUKS_BLOG_AUTH_GOOGLE_CLIENT_ID="${FUKS_BLOG_AUTH_GOOGLE_CLIENT_ID}" \
          -e FUKS_BLOG_BACKEND_POSTGRES_PASSWORD="${FUKS_BLOG_BACKEND_POSTGRES_PASSWORD}" \
          -e FUKS_BLOG_BACKEND_POSTGRES_USER="${FUKS_BLOG_BACKEND_POSTGRES_USER}" \
          -e FUKS_BLOG_BACKEND_POSTGRES_HOST="${FUKS_BLOG_BACKEND_POSTGRES_HOST}" \
          -e FUKS_BLOG_AUTH_JWT_SECRET="${FUKS_BLOG_AUTH_JWT_SECRET}" \
          -e PERSONAL_NPM_TOKEN="${PERSONAL_NPM_TOKEN}" \
          -e MAILER_USER="${MAILER_USER}" \
          -e MAILER_PASSWORD="${MAILER_PASSWORD}" \
          -e MAILER_HOST="${MAILER_HOST}" \
          -e GOOGLE_RECAPTCHA_SECRET_KEY="${GOOGLE_RECAPTCHA_SECRET_KEY}" \
          -v "/server/fuks_ru/auth.fuks.ru/var":/app/entries/auth-backend/var \
          -v "/server/fuks_ru/blog-backend.fuks.ru/var":/app/entries/blog-backend/var \
          -v "/server/fuks_ru/fuks.ru/var":/app/entries/blog-frontend/var \
          --network="fuks-ru" \
          difuks/fuks-blog \
          ${{ inputs.script }}
