name: 'Run node container'
description: 'Run node container'
inputs:
  script:
    description: 'Script for run'
    required: true
  detached:
    description: 'Detached docker mode'
    required: false
  secret-context:
    description: 'Secret params'
    required: true

runs:
  using: composite
  steps:
    - name: Run node script
      uses: ./.github/actions/ssh-script
      with:
        secret-context: ${{ inputs.secret-context }}
        script: |
          docker run --name fuks-blog \
          --rm ${{ inputs.detached && '-d' }} \
          -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
          -e POSTGRES_USER="${POSTGRES_USER}" \
          -e POSTGRES_HOST="${POSTGRES_HOST}" \
          -e PERSONAL_NPM_TOKEN="${PERSONAL_NPM_TOKEN}" \
          -v "/server/fuks-blog/blog-backend.fuks.ru/var":/app/entries/backend/var \
          -v "/server/fuks-blog/fuks.ru/var":/app/entries/frontend/var \
          --network="fuks-ru" \
          difuks/fuks-blog \
          ${{ inputs.script }}
