/**
 * Коды системных ошибок.
 */
export enum ErrorCode {
  GOOGLE_AUTH_PAYLOAD_EMPTY = 200,
  GOOGLE_AUTH_EMAIL_NOT_FOUND = 201,
  BASIC_AUTH_INCORRECT_EMAIL_OR_PASSWORD = 300,
  USER_ALREADY_EXISTS = 400,
  USER_NOT_FOUND = 401,
}
