name: 'Run ssh script'
description: 'Run ssh script'
inputs:
  script:
    description: 'Script for run'
    required: true
  secret-context:
    description: 'Secret params'
    required: true

runs:
  using: composite
  steps:
    - name: Run node script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ fromJson(inputs.secret-context).SSH_HOST }}
        username: ${{ fromJson(inputs.secret-context).SSH_USERNAME }}
        key: ${{ fromJson(inputs.secret-context).SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          export FUKS_BLOG_POSTGRES_PASSWORD="${{ fromJson(inputs.secret-context).FUKS_BLOG_POSTGRES_PASSWORD }}"
          export FUKS_BLOG_POSTGRES_USER="${{ fromJson(inputs.secret-context).FUKS_BLOG_POSTGRES_USER }}"
          export FUKS_BLOG_POSTGRES_HOST="fuks-blog-postgres"
  
          export PERSONAL_NPM_TOKEN="${{ fromJson(inputs.secret-context).PERSONAL_NPM_TOKEN }}"

          ${{inputs.script}}
