name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_RECAPTCHA_CLIENT_KEY: ${{ secrets.GOOGLE_RECAPTCHA_CLIENT_KEY }}
      PERSONAL_NPM_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      FUKS_BLOG_AUTH_GOOGLE_CLIENT_ID: ${{ secrets.FUKS_BLOG_AUTH_GOOGLE_CLIENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 0

      - name: Install modules
        run: yarn install

      - name: Build libs
        run: yarn build:lib

      - name: Eslint
        run: yarn lint

      - name: E2E tests
        run: yarn e2e

      - name: Build entries
        run: yarn build

      - name: Build typedoc
        run: yarn typedoc

      - name: Check packages versions
        run: yarn version check

      - name: Apply versions
        run: yarn version apply --all

      - name: Publish packages
        run: yarn workspaces foreach --include "@difuks/{common,common-backend,common-frontend,ui,auth-backend,blog-backend}" --interlaced --verbose npm publish --tolerate-republish

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            ci: Release packages
            
            [skip ci]

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Node build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/node/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fuks-blog:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Nginx build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/nginx/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fuks-blog-nginx:latest

  deploy:
    name: Deploy

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Stop and remove docker containers and remove images
        uses: ./.github/actions/ssh-script
        with:
          secret-context: ${{ toJson(secrets) }}
          script: |
            docker container stop $(docker container ls -q --filter name='fuks-blog') || true
            docker ps --filter name='fuks-blog' -aq | xargs docker stop | xargs docker rm || true
            docker rmi $(docker images | grep 'fuks-blog') || true

      - name: Pull docker containers
        uses: ./.github/actions/ssh-script
        with:
          secret-context: ${{ toJson(secrets) }}
          script: |
            docker pull difuks/fuks-blog
            docker pull difuks/fuks-blog-nginx

      - name: Run auth database
        uses: ./.github/actions/ssh-script
        with:
          secret-context: ${{ toJson(secrets) }}
          script: |
            docker run --name fuks-blog-auth-postgres \
            --rm -d \
            -e POSTGRES_PASSWORD="${FUKS_BLOG_AUTH_POSTGRES_PASSWORD}" \
            -e POSTGRES_USER="${FUKS_BLOG_AUTH_POSTGRES_USER}" \
            -e POSTGRES_DB=auth \
            -e PGDATA=/var/lib/postgresql/data/pgdata \
            -v "/server/fuks-blog/auth-backend-postgres/var":/var/lib/postgresql/data \
            --network="fuks-ru" \
            postgres:14.2-alpine

      - name: Run blog backend database
        uses: ./.github/actions/ssh-script
        with:
          secret-context: ${{ toJson(secrets) }}
          script: |
            docker run --name fuks-blog-backend-postgres \
            --rm -d \
            -e POSTGRES_PASSWORD="${FUKS_BLOG_BACKEND_POSTGRES_PASSWORD}" \
            -e POSTGRES_USER="${FUKS_BLOG_BACKEND_POSTGRES_USER}" \
            -e POSTGRES_DB=blog \
            -e PGDATA=/var/lib/postgresql/data/pgdata \
            -v "/server/fuks-blog/blog-backend-postgres/var":/var/lib/postgresql/data \
            --network="fuks-ru" \
            postgres:14.2-alpine

      - name: Run migrations
        uses: ./.github/actions/run-node
        with:
          secret-context: ${{ toJson(secrets) }}
          script: yarn prod:migration:run

      - name: Run node
        uses: ./.github/actions/run-node
        with:
          secret-context: ${{ toJson(secrets) }}
          script: yarn prod
          detached: true

      - name: Sleep for wait node start
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Run nginx
        uses: ./.github/actions/ssh-script
        with:
          secret-context: ${{ toJson(secrets) }}
          script: |
            docker run --name fuks-blog-nginx \
            --rm -d \
            --network="fuks-ru" \
            difuks/fuks-blog-nginx

  notification:
      name: Notification

      needs: [build, deploy]

      runs-on: ubuntu-latest

      if: always()

      steps:
        - name: Send telegram message
          uses: appleboy/telegram-action@master
          env:
            COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}}
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            format: markdown
            message: |
              Build *${{ needs.build.result == 'success' && '✅' || '⛔️' }}* Deploy *${{ needs.deploy.result == 'success' && '✅' || '⛔️' }}*

              *${{ github.actor }}* created [commit](${{ env.COMMIT_URL }})
  
              [Build and deploy](${{ env.COMMIT_URL }}/checks)
